language : csharp
os: windows
mono: none

install:
  - choco install dotnetcore-sdk

script:
  - dotnet restore 
  - dotnet build

# dotnet: 3.1.201 is not working on 'os:windows'
# some workaround with choco
# https://travis-ci.community/t/dotnet-core-3-1-1-on-windows/6609/2
